# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: embed_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x65mbed_service.proto\x12\ncom.cognix\"/\n\x0c\x45mbedRequest\x12\x10\n\x08\x63ontents\x18\x01 \x03(\t\x12\r\n\x05model\x18\x02 \x01(\t\"4\n\x11\x45mbedResponseItem\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x0e\n\x06vector\x18\x02 \x03(\x02\"B\n\rEmbedResponse\x12\x31\n\nembeddings\x18\x01 \x03(\x0b\x32\x1d.com.cognix.EmbedResponseItem2U\n\x0c\x45mbedService\x12\x45\n\x0cGetEmbedding\x12\x18.com.cognix.EmbedRequest\x1a\x19.com.cognix.EmbedResponse\"\x00\x42\x1aZ\x18\x62\x61\x63kend/core/proto;protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embed_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\030backend/core/proto;proto'
  _globals['_EMBEDREQUEST']._serialized_start=35
  _globals['_EMBEDREQUEST']._serialized_end=82
  _globals['_EMBEDRESPONSEITEM']._serialized_start=84
  _globals['_EMBEDRESPONSEITEM']._serialized_end=136
  _globals['_EMBEDRESPONSE']._serialized_start=138
  _globals['_EMBEDRESPONSE']._serialized_end=204
  _globals['_EMBEDSERVICE']._serialized_start=206
  _globals['_EMBEDSERVICE']._serialized_end=291
# @@protoc_insertion_point(module_scope)
