# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file_type.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x66ile_type.proto\x12\ncom.cognix*\xff\x01\n\x08\x46ileType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x07\n\x03PDF\x10\x01\x12\x07\n\x03XPS\x10\x02\x12\x07\n\x03TXT\x10\x03\x12\x08\n\x04\x44OCX\x10\x04\x12\x07\n\x03\x44OC\x10\x05\x12\x08\n\x04XLSX\x10\x06\x12\x07\n\x03XLS\x10\x07\x12\x08\n\x04PPTX\x10\x08\x12\x07\n\x03PPT\x10\t\x12\x08\n\x04HWPX\x10\n\x12\x08\n\x04\x45PUB\x10\x0b\x12\x08\n\x04MOBI\x10\x0c\x12\x07\n\x03\x46\x42\x32\x10\r\x12\x07\n\x03\x43\x42Z\x10\x0e\x12\x06\n\x02MD\x10\x0f\x12\x07\n\x03URL\x10\x10\x12\x06\n\x02YT\x10\x11\x12\x07\n\x03MP4\x10\x12\x12\x07\n\x03MP3\x10\x13\x12\x08\n\x04MPEG\x10\x14\x12\x08\n\x04MPGA\x10\x15\x12\x07\n\x03M4A\x10\x16\x12\x07\n\x03WAV\x10\x17\x12\x08\n\x04WEBM\x10\x18\x12\x07\n\x03MOV\x10\x19\x42\x1aZ\x18\x62\x61\x63kend/core/proto;protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_type_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\030backend/core/proto;proto'
  _globals['_FILETYPE']._serialized_start=32
  _globals['_FILETYPE']._serialized_end=287
# @@protoc_insertion_point(module_scope)
