# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transformer_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19transformer_service.proto\x12\ncom.cognix\"y\n\x0fSemanticRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\x12\x11\n\tthreshold\x18\x03 \x01(\x02\x12\x33\n\x0fsimilarity_type\x18\x07 \x01(\x0e\x32\x1a.com.cognix.SimilarityType\"\"\n\x10SemanticResponse\x12\x0e\n\x06\x63hunks\x18\x01 \x03(\t*(\n\x0eSimilarityType\x12\n\n\x06\x43OSINE\x10\x00\x12\n\n\x06\x44IRECT\x10\x01\x32\x62\n\x12TransformerService\x12L\n\rSemanticSplit\x12\x1b.com.cognix.SemanticRequest\x1a\x1c.com.cognix.SemanticResponse\"\x00\x42\x1aZ\x18\x62\x61\x63kend/core/proto;protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transformer_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\030backend/core/proto;proto'
  _globals['_SIMILARITYTYPE']._serialized_start=200
  _globals['_SIMILARITYTYPE']._serialized_end=240
  _globals['_SEMANTICREQUEST']._serialized_start=41
  _globals['_SEMANTICREQUEST']._serialized_end=162
  _globals['_SEMANTICRESPONSE']._serialized_start=164
  _globals['_SEMANTICRESPONSE']._serialized_end=198
  _globals['_TRANSFORMERSERVICE']._serialized_start=242
  _globals['_TRANSFORMERSERVICE']._serialized_end=340
# @@protoc_insertion_point(module_scope)
