global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets: [ ]
      scheme: http
      timeout: 10s
      api_version: v1

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  # external_labels:
  #  monitor: 'cognix-monitor'

# A scrape configuration containing one endpoint to scrape:
# Here it's Prometheus itself.

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
#  - job_name: 'prometheus'
#    # Override the global default and scrape targets from this job every 5 seconds.
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['localhost:9090']

## disabled to get host system logs
#  - job_name: system
#    static_configs:
#      - targets:
#          - localhost
#        labels:
#          job: varlogs
#          __path__: /var/log/*log

  # Example job for node_exporter
  - job_name: 'node-exporter'
    static_configs:
    - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
    - targets: ['cadvisor:8080']

  - job_name: 'nats-exporter'
    static_configs:
    - targets: [ 'nats-exporter:7777' ]

  - job_name: 'milvus-standalone'
    static_configs:
    - targets: [ 'milvus-standalone:9091' ]

  - job_name: 'prometheus'
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
      - localhost:9090
      -
  - job_name: 'cockroachdb'
    metrics_path: '/_status/vars'
    # Insecure mode:
    scheme: 'http'
    # Secure mode:
    # scheme: 'https'
    tls_config:
      insecure_skip_verify: true
    static_configs:
    - targets: ['cockroach:8080']
      labels:
        cluster: 'my-cockroachdb-cluster'

  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker_logs
          __path__: /var/lib/docker/containers/*/*-json.log