# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vision_data.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import cognix_lib.gen_types.file_type_pb2 as file__type__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11vision_data.proto\x12\ncom.cognix\x1a\x0f\x66ile_type.proto\"\xb3\x01\n\nVisionData\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x13\n\x0b\x64ocument_id\x18\x02 \x01(\x03\x12\x14\n\x0c\x63onnector_id\x18\x03 \x01(\x03\x12\'\n\tfile_type\x18\x04 \x01(\x0e\x32\x14.com.cognix.FileType\x12\x17\n\x0f\x63ollection_name\x18\x05 \x01(\t\x12\x12\n\nmodel_name\x18\x06 \x01(\t\x12\x17\n\x0fmodel_dimension\x18\x07 \x01(\x05\x42\x1aZ\x18\x62\x61\x63kend/core/proto;protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vision_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\030backend/core/proto;proto'
  _globals['_VISIONDATA']._serialized_start=51
  _globals['_VISIONDATA']._serialized_end=230
# @@protoc_insertion_point(module_scope)
