// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: config_map.proto

package proto

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigMapList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ConfigMapList) Reset() {
	*x = ConfigMapList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_map_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigMapList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigMapList) ProtoMessage() {}

func (x *ConfigMapList) ProtoReflect() protoreflect.Message {
	mi := &file_config_map_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigMapList.ProtoReflect.Descriptor instead.
func (*ConfigMapList) Descriptor() ([]byte, []int) {
	return file_config_map_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigMapList) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ConfigMapRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ConfigMapRecord) Reset() {
	*x = ConfigMapRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_map_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigMapRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigMapRecord) ProtoMessage() {}

func (x *ConfigMapRecord) ProtoReflect() protoreflect.Message {
	mi := &file_config_map_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigMapRecord.ProtoReflect.Descriptor instead.
func (*ConfigMapRecord) Descriptor() ([]byte, []int) {
	return file_config_map_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigMapRecord) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConfigMapRecord) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ConfigMapListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []*ConfigMapRecord `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *ConfigMapListResponse) Reset() {
	*x = ConfigMapListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_map_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigMapListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigMapListResponse) ProtoMessage() {}

func (x *ConfigMapListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_map_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigMapListResponse.ProtoReflect.Descriptor instead.
func (*ConfigMapListResponse) Descriptor() ([]byte, []int) {
	return file_config_map_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigMapListResponse) GetValues() []*ConfigMapRecord {
	if x != nil {
		return x.Values
	}
	return nil
}

type ConfigMapSave struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value *ConfigMapRecord `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ConfigMapSave) Reset() {
	*x = ConfigMapSave{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_map_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigMapSave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigMapSave) ProtoMessage() {}

func (x *ConfigMapSave) ProtoReflect() protoreflect.Message {
	mi := &file_config_map_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigMapSave.ProtoReflect.Descriptor instead.
func (*ConfigMapSave) Descriptor() ([]byte, []int) {
	return file_config_map_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigMapSave) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigMapSave) GetValue() *ConfigMapRecord {
	if x != nil {
		return x.Value
	}
	return nil
}

type ConfigMapDelete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Key  string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *ConfigMapDelete) Reset() {
	*x = ConfigMapDelete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_map_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigMapDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigMapDelete) ProtoMessage() {}

func (x *ConfigMapDelete) ProtoReflect() protoreflect.Message {
	mi := &file_config_map_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigMapDelete.ProtoReflect.Descriptor instead.
func (*ConfigMapDelete) Descriptor() ([]byte, []int) {
	return file_config_map_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigMapDelete) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigMapDelete) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

var File_config_map_proto protoreflect.FileDescriptor

var file_config_map_proto_rawDesc = []byte{
	0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x6d, 0x61, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x67, 0x6e, 0x69, 0x78, 0x1a, 0x1b,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x23, 0x0a, 0x0d, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4d, 0x61, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x39, 0x0a, 0x0f, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x4c, 0x0a, 0x15, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4d, 0x61, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x67, 0x6e, 0x69,
	0x78, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x56, 0x0a, 0x0d, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x4d, 0x61, 0x70, 0x53, 0x61, 0x76, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x31,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x67, 0x6e, 0x69, 0x78, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x37, 0x0a, 0x0f, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4d, 0x61, 0x70, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x32, 0xd4, 0x01, 0x0a, 0x09, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4d, 0x61, 0x70, 0x12, 0x49, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x19, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x67, 0x6e, 0x69, 0x78,
	0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4d, 0x61, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x21,
	0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x67, 0x6e, 0x69, 0x78, 0x2e, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x4d, 0x61, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x04, 0x53, 0x61, 0x76, 0x65, 0x12, 0x19, 0x2e, 0x63, 0x6f,
	0x6d, 0x2e, 0x63, 0x6f, 0x67, 0x6e, 0x69, 0x78, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4d,
	0x61, 0x70, 0x53, 0x61, 0x76, 0x65, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00,
	0x12, 0x3f, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1b, 0x2e, 0x63, 0x6f, 0x6d,
	0x2e, 0x63, 0x6f, 0x67, 0x6e, 0x69, 0x78, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4d, 0x61,
	0x70, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x00, 0x42, 0x1a, 0x5a, 0x18, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x63, 0x6f, 0x72,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_config_map_proto_rawDescOnce sync.Once
	file_config_map_proto_rawDescData = file_config_map_proto_rawDesc
)

func file_config_map_proto_rawDescGZIP() []byte {
	file_config_map_proto_rawDescOnce.Do(func() {
		file_config_map_proto_rawDescData = protoimpl.X.CompressGZIP(file_config_map_proto_rawDescData)
	})
	return file_config_map_proto_rawDescData
}

var file_config_map_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_config_map_proto_goTypes = []interface{}{
	(*ConfigMapList)(nil),         // 0: com.cognix.ConfigMapList
	(*ConfigMapRecord)(nil),       // 1: com.cognix.ConfigMapRecord
	(*ConfigMapListResponse)(nil), // 2: com.cognix.ConfigMapListResponse
	(*ConfigMapSave)(nil),         // 3: com.cognix.ConfigMapSave
	(*ConfigMapDelete)(nil),       // 4: com.cognix.ConfigMapDelete
	(*empty.Empty)(nil),           // 5: google.protobuf.Empty
}
var file_config_map_proto_depIdxs = []int32{
	1, // 0: com.cognix.ConfigMapListResponse.values:type_name -> com.cognix.ConfigMapRecord
	1, // 1: com.cognix.ConfigMapSave.value:type_name -> com.cognix.ConfigMapRecord
	0, // 2: com.cognix.ConfigMap.GetList:input_type -> com.cognix.ConfigMapList
	3, // 3: com.cognix.ConfigMap.Save:input_type -> com.cognix.ConfigMapSave
	4, // 4: com.cognix.ConfigMap.Delete:input_type -> com.cognix.ConfigMapDelete
	2, // 5: com.cognix.ConfigMap.GetList:output_type -> com.cognix.ConfigMapListResponse
	5, // 6: com.cognix.ConfigMap.Save:output_type -> google.protobuf.Empty
	5, // 7: com.cognix.ConfigMap.Delete:output_type -> google.protobuf.Empty
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_config_map_proto_init() }
func file_config_map_proto_init() {
	if File_config_map_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_config_map_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigMapList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_map_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigMapRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_map_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigMapListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_map_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigMapSave); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_map_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigMapDelete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_config_map_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_config_map_proto_goTypes,
		DependencyIndexes: file_config_map_proto_depIdxs,
		MessageInfos:      file_config_map_proto_msgTypes,
	}.Build()
	File_config_map_proto = out.File
	file_config_map_proto_rawDesc = nil
	file_config_map_proto_goTypes = nil
	file_config_map_proto_depIdxs = nil
}
