// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: embed_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmbedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Contents []string `protobuf:"bytes,1,rep,name=contents,proto3" json:"contents,omitempty"`
	Model    string   `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
}

func (x *EmbedRequest) Reset() {
	*x = EmbedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_embed_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmbedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedRequest) ProtoMessage() {}

func (x *EmbedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_embed_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedRequest.ProtoReflect.Descriptor instead.
func (*EmbedRequest) Descriptor() ([]byte, []int) {
	return file_embed_service_proto_rawDescGZIP(), []int{0}
}

func (x *EmbedRequest) GetContents() []string {
	if x != nil {
		return x.Contents
	}
	return nil
}

func (x *EmbedRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type EmbedResponseItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string    `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Vector  []float32 `protobuf:"fixed32,2,rep,packed,name=vector,proto3" json:"vector,omitempty"`
}

func (x *EmbedResponseItem) Reset() {
	*x = EmbedResponseItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_embed_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmbedResponseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedResponseItem) ProtoMessage() {}

func (x *EmbedResponseItem) ProtoReflect() protoreflect.Message {
	mi := &file_embed_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedResponseItem.ProtoReflect.Descriptor instead.
func (*EmbedResponseItem) Descriptor() ([]byte, []int) {
	return file_embed_service_proto_rawDescGZIP(), []int{1}
}

func (x *EmbedResponseItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *EmbedResponseItem) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

type EmbedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Embeddings []*EmbedResponseItem `protobuf:"bytes,1,rep,name=embeddings,proto3" json:"embeddings,omitempty"` // List of embedding items
}

func (x *EmbedResponse) Reset() {
	*x = EmbedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_embed_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmbedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedResponse) ProtoMessage() {}

func (x *EmbedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_embed_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedResponse.ProtoReflect.Descriptor instead.
func (*EmbedResponse) Descriptor() ([]byte, []int) {
	return file_embed_service_proto_rawDescGZIP(), []int{2}
}

func (x *EmbedResponse) GetEmbeddings() []*EmbedResponseItem {
	if x != nil {
		return x.Embeddings
	}
	return nil
}

var File_embed_service_proto protoreflect.FileDescriptor

var file_embed_service_proto_rawDesc = []byte{
	0x0a, 0x13, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x67, 0x6e, 0x69,
	0x78, 0x22, 0x40, 0x0a, 0x0c, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x22, 0x45, 0x0a, 0x11, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x02, 0x52, 0x06, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x22, 0x4e, 0x0a, 0x0d, 0x45, 0x6d,
	0x62, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0a, 0x65,
	0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1d, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x67, 0x6e, 0x69, 0x78, 0x2e, 0x45, 0x6d, 0x62,
	0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0a,
	0x65, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x32, 0x55, 0x0a, 0x0c, 0x45, 0x6d,
	0x62, 0x65, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x45, 0x0a, 0x0c, 0x47, 0x65,
	0x74, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x2e, 0x63, 0x6f, 0x6d,
	0x2e, 0x63, 0x6f, 0x67, 0x6e, 0x69, 0x78, 0x2e, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x67, 0x6e, 0x69,
	0x78, 0x2e, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x1a, 0x5a, 0x18, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x63, 0x6f, 0x72,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_embed_service_proto_rawDescOnce sync.Once
	file_embed_service_proto_rawDescData = file_embed_service_proto_rawDesc
)

func file_embed_service_proto_rawDescGZIP() []byte {
	file_embed_service_proto_rawDescOnce.Do(func() {
		file_embed_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_embed_service_proto_rawDescData)
	})
	return file_embed_service_proto_rawDescData
}

var file_embed_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_embed_service_proto_goTypes = []interface{}{
	(*EmbedRequest)(nil),      // 0: com.cognix.EmbedRequest
	(*EmbedResponseItem)(nil), // 1: com.cognix.EmbedResponseItem
	(*EmbedResponse)(nil),     // 2: com.cognix.EmbedResponse
}
var file_embed_service_proto_depIdxs = []int32{
	1, // 0: com.cognix.EmbedResponse.embeddings:type_name -> com.cognix.EmbedResponseItem
	0, // 1: com.cognix.EmbedService.GetEmbedding:input_type -> com.cognix.EmbedRequest
	2, // 2: com.cognix.EmbedService.GetEmbedding:output_type -> com.cognix.EmbedResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_embed_service_proto_init() }
func file_embed_service_proto_init() {
	if File_embed_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_embed_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmbedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_embed_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmbedResponseItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_embed_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmbedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_embed_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_embed_service_proto_goTypes,
		DependencyIndexes: file_embed_service_proto_depIdxs,
		MessageInfos:      file_embed_service_proto_msgTypes,
	}.Build()
	File_embed_service_proto = out.File
	file_embed_service_proto_rawDesc = nil
	file_embed_service_proto_goTypes = nil
	file_embed_service_proto_depIdxs = nil
}
