// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: file_type.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileType int32

const (
	// ORCHESTRATOR SEND TO CONNECTOR:
	FileType_UNKNOWN FileType = 0
	FileType_PDF     FileType = 1
	FileType_XPS     FileType = 2
	FileType_TXT     FileType = 3
	FileType_DOCX    FileType = 4
	FileType_DOC     FileType = 5
	FileType_XLSX    FileType = 6
	FileType_XLS     FileType = 7
	FileType_PPTX    FileType = 8
	FileType_PPT     FileType = 9
	FileType_HWPX    FileType = 10
	FileType_EPUB    FileType = 11
	FileType_MOBI    FileType = 12
	FileType_FB2     FileType = 13
	FileType_CBZ     FileType = 14
	FileType_MD      FileType = 15
	// ORCHESTRATOR SEND TO SEMANTIC
	FileType_URL FileType = 16
	FileType_YT  FileType = 17
	// ORCHESTRATOR SEND TO WHISPER
	FileType_MP4  FileType = 18
	FileType_MP3  FileType = 19
	FileType_MPEG FileType = 20
	FileType_MPGA FileType = 21
	FileType_M4A  FileType = 22
	FileType_WAV  FileType = 23
	FileType_WEBM FileType = 24
	FileType_MOV  FileType = 25
)

// Enum value maps for FileType.
var (
	FileType_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "PDF",
		2:  "XPS",
		3:  "TXT",
		4:  "DOCX",
		5:  "DOC",
		6:  "XLSX",
		7:  "XLS",
		8:  "PPTX",
		9:  "PPT",
		10: "HWPX",
		11: "EPUB",
		12: "MOBI",
		13: "FB2",
		14: "CBZ",
		15: "MD",
		16: "URL",
		17: "YT",
		18: "MP4",
		19: "MP3",
		20: "MPEG",
		21: "MPGA",
		22: "M4A",
		23: "WAV",
		24: "WEBM",
		25: "MOV",
	}
	FileType_value = map[string]int32{
		"UNKNOWN": 0,
		"PDF":     1,
		"XPS":     2,
		"TXT":     3,
		"DOCX":    4,
		"DOC":     5,
		"XLSX":    6,
		"XLS":     7,
		"PPTX":    8,
		"PPT":     9,
		"HWPX":    10,
		"EPUB":    11,
		"MOBI":    12,
		"FB2":     13,
		"CBZ":     14,
		"MD":      15,
		"URL":     16,
		"YT":      17,
		"MP4":     18,
		"MP3":     19,
		"MPEG":    20,
		"MPGA":    21,
		"M4A":     22,
		"WAV":     23,
		"WEBM":    24,
		"MOV":     25,
	}
)

func (x FileType) Enum() *FileType {
	p := new(FileType)
	*p = x
	return p
}

func (x FileType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileType) Descriptor() protoreflect.EnumDescriptor {
	return file_file_type_proto_enumTypes[0].Descriptor()
}

func (FileType) Type() protoreflect.EnumType {
	return &file_file_type_proto_enumTypes[0]
}

func (x FileType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileType.Descriptor instead.
func (FileType) EnumDescriptor() ([]byte, []int) {
	return file_file_type_proto_rawDescGZIP(), []int{0}
}

var File_file_type_proto protoreflect.FileDescriptor

var file_file_type_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0a, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x67, 0x6e, 0x69, 0x78, 0x2a, 0xff, 0x01,
	0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e,
	0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x50, 0x44, 0x46, 0x10, 0x01,
	0x12, 0x07, 0x0a, 0x03, 0x58, 0x50, 0x53, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x54, 0x58, 0x54,
	0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x4f, 0x43, 0x58, 0x10, 0x04, 0x12, 0x07, 0x0a, 0x03,
	0x44, 0x4f, 0x43, 0x10, 0x05, 0x12, 0x08, 0x0a, 0x04, 0x58, 0x4c, 0x53, 0x58, 0x10, 0x06, 0x12,
	0x07, 0x0a, 0x03, 0x58, 0x4c, 0x53, 0x10, 0x07, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x50, 0x54, 0x58,
	0x10, 0x08, 0x12, 0x07, 0x0a, 0x03, 0x50, 0x50, 0x54, 0x10, 0x09, 0x12, 0x08, 0x0a, 0x04, 0x48,
	0x57, 0x50, 0x58, 0x10, 0x0a, 0x12, 0x08, 0x0a, 0x04, 0x45, 0x50, 0x55, 0x42, 0x10, 0x0b, 0x12,
	0x08, 0x0a, 0x04, 0x4d, 0x4f, 0x42, 0x49, 0x10, 0x0c, 0x12, 0x07, 0x0a, 0x03, 0x46, 0x42, 0x32,
	0x10, 0x0d, 0x12, 0x07, 0x0a, 0x03, 0x43, 0x42, 0x5a, 0x10, 0x0e, 0x12, 0x06, 0x0a, 0x02, 0x4d,
	0x44, 0x10, 0x0f, 0x12, 0x07, 0x0a, 0x03, 0x55, 0x52, 0x4c, 0x10, 0x10, 0x12, 0x06, 0x0a, 0x02,
	0x59, 0x54, 0x10, 0x11, 0x12, 0x07, 0x0a, 0x03, 0x4d, 0x50, 0x34, 0x10, 0x12, 0x12, 0x07, 0x0a,
	0x03, 0x4d, 0x50, 0x33, 0x10, 0x13, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x50, 0x45, 0x47, 0x10, 0x14,
	0x12, 0x08, 0x0a, 0x04, 0x4d, 0x50, 0x47, 0x41, 0x10, 0x15, 0x12, 0x07, 0x0a, 0x03, 0x4d, 0x34,
	0x41, 0x10, 0x16, 0x12, 0x07, 0x0a, 0x03, 0x57, 0x41, 0x56, 0x10, 0x17, 0x12, 0x08, 0x0a, 0x04,
	0x57, 0x45, 0x42, 0x4d, 0x10, 0x18, 0x12, 0x07, 0x0a, 0x03, 0x4d, 0x4f, 0x56, 0x10, 0x19, 0x42,
	0x1a, 0x5a, 0x18, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_file_type_proto_rawDescOnce sync.Once
	file_file_type_proto_rawDescData = file_file_type_proto_rawDesc
)

func file_file_type_proto_rawDescGZIP() []byte {
	file_file_type_proto_rawDescOnce.Do(func() {
		file_file_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_file_type_proto_rawDescData)
	})
	return file_file_type_proto_rawDescData
}

var file_file_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_file_type_proto_goTypes = []interface{}{
	(FileType)(0), // 0: com.cognix.FileType
}
var file_file_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_file_type_proto_init() }
func file_file_type_proto_init() {
	if File_file_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_file_type_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_file_type_proto_goTypes,
		DependencyIndexes: file_file_type_proto_depIdxs,
		EnumInfos:         file_file_type_proto_enumTypes,
	}.Build()
	File_file_type_proto = out.File
	file_file_type_proto_rawDesc = nil
	file_file_type_proto_goTypes = nil
	file_file_type_proto_depIdxs = nil
}
