name: Build orchestrator service

# on:
#   push:
#     tags:
#       - '*'
on:
  push:
    branches:
      - main
    paths:
      - 'src/backend/orchestrator/**'
      - 'src/backend/core/**'
      - 'src/backend/go.mod'
      - '.github/workflows/orchestrator-service-build.yml'
env:
  RGNAME: AKS_RG
  ACRNAME: cognixacr
  AKSNAME: Cognix_AKS
  GITHUB_SHA: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to ACR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.ACRNAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Orchestrator Service Image Docker Build and Push
      uses: docker/build-push-action@v2
      with:
        context: ./src/backend
        file: ./src/backend/orchestrator/Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          ${{ env.ACRNAME }}.azurecr.io/cognix/orchestratorservice:${{env.GITHUB_SHA}}
        build-args: |
          COGNIX_VERSION=${{env.GITHUB_SHA}}
          service=orchestrator

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Get AKS kubeconfig
      run: az aks get-credentials --resource-group $RGNAME --name $AKSNAME

    - name: Update Orchestrator server manifest
      run:
        sed -ie "s/orchestratorservice:main/orchestratorservice:${{env.GITHUB_SHA}}/g" ./src/backend/orchestrator/service-deployment.yaml

    - name: Deploy Orchestrator server manifests
      run: |
        kubectl apply -f ./src/backend/orchestrator/service-deployment.yaml 

    - name: Delete Orchestrator server pod
      run: |
        kubectl rollout restart deploy/orchestratorservice