apiVersion: apps/v1
kind: Deployment
metadata:
  name: transformer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transformer
  template:
    metadata:
      labels:
        app: transformer
    spec:
      containers:
      - name: transformer
        image: cognixacr.azurecr.io/cognix/transformer:main
        envFrom:
        - configMapRef:
            name: transformer-srv
        ports:
        - containerPort: 50052
        volumeMounts:
        - mountPath: /models
          name: models
        imagePullPolicy: Always
      imagePullSecrets:
        - name: pullsecret
      volumes:
        - name: models
          persistentVolumeClaim:
            claimName: models
---
apiVersion: v1
kind: Service
metadata:
  name: transformer
spec:
  selector:
    app: transformer
  ports:
    - protocol: TCP
      port: 50052
      targetPort: 50052
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: azurefile-csi
